/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.PQR.GUI;

import com.PQR.controller.UsuarioControl;
import java.awt.*;
import java.awt.event.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author EQUIPO
 */
public class ArquitecturaUI extends javax.swing.JFrame {

    /**
     * Creates new form ArquitecturaUI
     */
    private UsuarioControl uControl;

    public ArquitecturaUI() {
        initComponents();
        uControl = new UsuarioControl();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        crear_pqrs = new javax.swing.JDialog();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel_crear_pqr = new javax.swing.JPanel();
        label_titulo = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jTextField_solicitud_asunto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jComboBox_solicitud_tipo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_solicitud_cuerpo = new javax.swing.JTextArea();
        jButton_cancelar_pqr = new javax.swing.JButton();
        jButton_crear_pqr = new javax.swing.JButton();
        panel_formulario1 = new javax.swing.JPanel();
        label_pqrs = new java.awt.Label();
        panel1 = new java.awt.Panel();
        jLabel_solicitud = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jComboBox_filtro_tipo_solicitud = new javax.swing.JComboBox<>();
        jComboBox_filtro_estado_solicitud = new javax.swing.JComboBox<>();
        jDateChooser_filtro_fecha_respuesta = new com.toedter.calendar.JDateChooser();
        jDateChooser_filtro_fecha_cierre = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable_info_pqrs = new javax.swing.JTable();
        jButton_cargar_mis_pqr = new javax.swing.JButton();
        info_solicitud = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea_info_solicitud = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea_anotaciones = new javax.swing.JTextArea();
        jButton_añadir_anotacion = new javax.swing.JButton();
        jPanel_inicio = new javax.swing.JPanel();
        jTabbedPane_inicio = new javax.swing.JTabbedPane();
        panel_formulario = new javax.swing.JPanel();
        jLabel_correo = new javax.swing.JLabel();
        jLabel_contraseña = new javax.swing.JLabel();
        jButton_registro = new javax.swing.JButton();
        jLabel_nombre = new javax.swing.JLabel();
        jPassword_registro = new javax.swing.JPasswordField();
        jTextField_correo_registro = new javax.swing.JTextField();
        jTextField_nombre_registro = new javax.swing.JTextField();
        jLabel_respuesta_registro = new javax.swing.JLabel();
        jPanel_iniciarsesion = new javax.swing.JPanel();
        jLabel_correo1 = new javax.swing.JLabel();
        jTextField_correo_inicio_sesion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPassword_inicio_sesion = new javax.swing.JPasswordField();
        jButton_inicio_sesion = new javax.swing.JButton();
        jLabel_respuesta_login = new javax.swing.JLabel();

        crear_pqrs.setMinimumSize(new java.awt.Dimension(550, 400));

        jTabbedPane2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PQRs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jTabbedPane2.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jPanel_crear_pqr.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_crear_pqr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_titulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_titulo.setText("Nueva Solicitud");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Asunto");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Tipo de solicitud");

        jComboBox_solicitud_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "peticion", "queja", "reclamo" }));
        jComboBox_solicitud_tipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_solicitud_tipoItemStateChanged(evt);
            }
        });
        jComboBox_solicitud_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_solicitud_tipoActionPerformed(evt);
            }
        });

        jTextArea_solicitud_cuerpo.setColumns(20);
        jTextArea_solicitud_cuerpo.setRows(5);
        jScrollPane1.setViewportView(jTextArea_solicitud_cuerpo);

        jButton_cancelar_pqr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_cancelar_pqr.setText("Cancelar");
        jButton_cancelar_pqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cancelar_pqrActionPerformed(evt);
            }
        });

        jButton_crear_pqr.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_crear_pqr.setText("Crear Solicitud");
        jButton_crear_pqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_crear_pqrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_crear_pqrLayout = new javax.swing.GroupLayout(jPanel_crear_pqr);
        jPanel_crear_pqr.setLayout(jPanel_crear_pqrLayout);
        jPanel_crear_pqrLayout.setHorizontalGroup(
            jPanel_crear_pqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_crear_pqrLayout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_crear_pqrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_crear_pqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel_crear_pqrLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton_cancelar_pqr, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(64, 64, 64)
                        .addComponent(jButton_crear_pqr, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_crear_pqrLayout.createSequentialGroup()
                        .addGroup(jPanel_crear_pqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_crear_pqrLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 285, Short.MAX_VALUE))
                            .addComponent(jTextField_solicitud_asunto))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_crear_pqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jComboBox_solicitud_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(21, 21, 21))
        );
        jPanel_crear_pqrLayout.setVerticalGroup(
            jPanel_crear_pqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_crear_pqrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_crear_pqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_crear_pqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_solicitud_asunto, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox_solicitud_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel_crear_pqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_crear_pqr, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(jButton_cancelar_pqr, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        label_titulo.getAccessibleContext().setAccessibleName("");

        jTabbedPane2.addTab("Crear PQR", jPanel_crear_pqr);

        panel_formulario1.setBackground(new java.awt.Color(255, 255, 255));
        panel_formulario1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        label_pqrs.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        label_pqrs.setText("PQRs");

        panel1.setLayout(new java.awt.GridLayout(2, 4, 4, 2));

        jLabel_solicitud.setText("Tipo de solicitud");
        panel1.add(jLabel_solicitud);

        jLabel5.setText("Estado de solicitud");
        panel1.add(jLabel5);

        jLabel6.setText("Fecha de repuesta");
        panel1.add(jLabel6);

        jLabel7.setText("Fecha de cierre");
        panel1.add(jLabel7);

        jComboBox_filtro_tipo_solicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "peticion", "queja", "reclamo" }));
        panel1.add(jComboBox_filtro_tipo_solicitud);

        jComboBox_filtro_estado_solicitud.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "radicada", "en_proceso", "resuelto", "cerrado" }));
        panel1.add(jComboBox_filtro_estado_solicitud);
        panel1.add(jDateChooser_filtro_fecha_respuesta);
        panel1.add(jDateChooser_filtro_fecha_cierre);

        jTable_info_pqrs.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTable_info_pqrs.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Asunto", "Tipo", "Estado", "Fecha creado", "Acciones"
            }
        ));
        jScrollPane2.setViewportView(jTable_info_pqrs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
        );

        jButton_cargar_mis_pqr.setText("cargar");
        jButton_cargar_mis_pqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_cargar_mis_pqrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_formulario1Layout = new javax.swing.GroupLayout(panel_formulario1);
        panel_formulario1.setLayout(panel_formulario1Layout);
        panel_formulario1Layout.setHorizontalGroup(
            panel_formulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formulario1Layout.createSequentialGroup()
                .addGroup(panel_formulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_formulario1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 506, Short.MAX_VALUE))
                    .addGroup(panel_formulario1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(panel_formulario1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(label_pqrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jButton_cargar_mis_pqr, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_formulario1Layout.setVerticalGroup(
            panel_formulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formulario1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_formulario1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label_pqrs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_cargar_mis_pqr))
                .addGap(4, 4, 4)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Mis PQRs", panel_formulario1);

        javax.swing.GroupLayout crear_pqrsLayout = new javax.swing.GroupLayout(crear_pqrs.getContentPane());
        crear_pqrs.getContentPane().setLayout(crear_pqrsLayout);
        crear_pqrsLayout.setHorizontalGroup(
            crear_pqrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_pqrsLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 545, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        crear_pqrsLayout.setVerticalGroup(
            crear_pqrsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(crear_pqrsLayout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Informacion de la solicitud");

        jTextArea_info_solicitud.setColumns(20);
        jTextArea_info_solicitud.setRows(5);
        jScrollPane3.setViewportView(jTextArea_info_solicitud);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Anotaciones");

        jTextArea_anotaciones.setColumns(20);
        jTextArea_anotaciones.setRows(5);
        jScrollPane4.setViewportView(jTextArea_anotaciones);

        jButton_añadir_anotacion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton_añadir_anotacion.setText("Añadir");
        jButton_añadir_anotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_añadir_anotacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel8)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton_añadir_anotacion)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(jButton_añadir_anotacion)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout info_solicitudLayout = new javax.swing.GroupLayout(info_solicitud.getContentPane());
        info_solicitud.getContentPane().setLayout(info_solicitudLayout);
        info_solicitudLayout.setHorizontalGroup(
            info_solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(info_solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(info_solicitudLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        info_solicitudLayout.setVerticalGroup(
            info_solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
            .addGroup(info_solicitudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(info_solicitudLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("principal"); // NOI18N

        jTabbedPane_inicio.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "PQRs", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BELOW_TOP, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jTabbedPane_inicio.setTabLayoutPolicy(javax.swing.JTabbedPane.SCROLL_TAB_LAYOUT);
        jTabbedPane_inicio.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        panel_formulario.setBackground(new java.awt.Color(255, 255, 255));
        panel_formulario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_correo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_correo.setText("Correo");

        jLabel_contraseña.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_contraseña.setText("Contraseña");

        jButton_registro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_registro.setText("Registrarse");
        jButton_registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_registroActionPerformed(evt);
            }
        });

        jLabel_nombre.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_nombre.setText("Nombre");

        javax.swing.GroupLayout panel_formularioLayout = new javax.swing.GroupLayout(panel_formulario);
        panel_formulario.setLayout(panel_formularioLayout);
        panel_formularioLayout.setHorizontalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPassword_registro)
                            .addComponent(jTextField_correo_registro)
                            .addComponent(jTextField_nombre_registro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panel_formularioLayout.createSequentialGroup()
                                .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_contraseña)
                                    .addComponent(jLabel_nombre)
                                    .addComponent(jLabel_correo))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panel_formularioLayout.createSequentialGroup()
                        .addGroup(panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_formularioLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel_respuesta_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_formularioLayout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jButton_registro)))
                        .addGap(0, 40, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_formularioLayout.setVerticalGroup(
            panel_formularioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_formularioLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel_nombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_nombre_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_correo)
                .addGap(5, 5, 5)
                .addComponent(jTextField_correo_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_contraseña)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassword_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel_respuesta_registro, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane_inicio.addTab("Registrarse", panel_formulario);

        jPanel_iniciarsesion.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_iniciarsesion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel_correo1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel_correo1.setText("Correo");

        jTextField_correo_inicio_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_correo_inicio_sesionActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Contraseña");

        jButton_inicio_sesion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton_inicio_sesion.setText("Iniciar Sesion");
        jButton_inicio_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_inicio_sesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_iniciarsesionLayout = new javax.swing.GroupLayout(jPanel_iniciarsesion);
        jPanel_iniciarsesion.setLayout(jPanel_iniciarsesionLayout);
        jPanel_iniciarsesionLayout.setHorizontalGroup(
            jPanel_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_iniciarsesionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel_correo1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_iniciarsesionLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jButton_inicio_sesion)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel_iniciarsesionLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addGroup(jPanel_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel_iniciarsesionLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel_respuesta_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTextField_correo_inicio_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPassword_inicio_sesion))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel_iniciarsesionLayout.setVerticalGroup(
            jPanel_iniciarsesionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_iniciarsesionLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel_correo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_correo_inicio_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPassword_inicio_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton_inicio_sesion, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_respuesta_login, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jTabbedPane_inicio.addTab("Iniciar Sesion", jPanel_iniciarsesion);

        javax.swing.GroupLayout jPanel_inicioLayout = new javax.swing.GroupLayout(jPanel_inicio);
        jPanel_inicio.setLayout(jPanel_inicioLayout);
        jPanel_inicioLayout.setHorizontalGroup(
            jPanel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 393, Short.MAX_VALUE)
            .addGroup(jPanel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane_inicio, javax.swing.GroupLayout.Alignment.TRAILING))
        );
        jPanel_inicioLayout.setVerticalGroup(
            jPanel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 354, Short.MAX_VALUE)
            .addGroup(jPanel_inicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_registroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_registroActionPerformed
        String correo = jTextField_correo_registro.getText();
        String nombre = jTextField_nombre_registro.getText();
        String password = jPassword_registro.getText();
        if (correo != null 
                && correo != "" 
                && nombre != null 
                && nombre != "" 
                && password != null 
                && password != "") {
            if (uControl.crearUsuario(nombre, password, nombre)) {               
               
                jLabel_respuesta_registro.setText("Registro exitoso, por favor inicie sesion.");
            } else {
                jLabel_respuesta_registro.setText("El usuario ya existe.");
            }
        }else{
            jLabel_respuesta_registro.setText("por favor complete los datos.");
        }


    }//GEN-LAST:event_jButton_registroActionPerformed

    private void jTextField_correo_inicio_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_correo_inicio_sesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_correo_inicio_sesionActionPerformed

    private void jComboBox_solicitud_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_solicitud_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_solicitud_tipoActionPerformed

    private void jButton_cancelar_pqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cancelar_pqrActionPerformed
        // TODO add your handling code here:
        jTextField_solicitud_asunto.setText("");
        jTextArea_solicitud_cuerpo.setText("");
        this.crear_pqrs.setVisible(false); 
        ArquitecturaUI a = new ArquitecturaUI();
        a.setVisible(true);
        //this.jPanel_inicio.setVisible(true);
    }//GEN-LAST:event_jButton_cancelar_pqrActionPerformed

    //boton inicio de sesión
    private void jButton_inicio_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_inicio_sesionActionPerformed

        String email = jTextField_correo_inicio_sesion.getText();
        String password = jPassword_inicio_sesion.getText();

        if (uControl.login(email, password)) {
            dispose();
            this.crear_pqrs.setVisible(true);          
        }

        this.jTextField_correo_inicio_sesion.setText("");
        this.jPassword_inicio_sesion.setText("");
        this.jLabel_respuesta_login.setText("Correo o contraseña incorrectos");

    }//GEN-LAST:event_jButton_inicio_sesionActionPerformed

    private void jButton_añadir_anotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_añadir_anotacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_añadir_anotacionActionPerformed

    private void jComboBox_solicitud_tipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_solicitud_tipoItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_solicitud_tipoItemStateChanged

    
    //crear solicitud
    private void jButton_crear_pqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_crear_pqrActionPerformed
        
        String asunto= jTextField_solicitud_asunto.getText();
        String cuerpo= jTextArea_solicitud_cuerpo.getText();
        String tipo=jComboBox_solicitud_tipo.getSelectedItem().toString();
        uControl.crearPQR(asunto, cuerpo, tipo);
        
    }//GEN-LAST:event_jButton_crear_pqrActionPerformed

    private void jButton_cargar_mis_pqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_cargar_mis_pqrActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = new DefaultTableModel();
        
        
        
    }//GEN-LAST:event_jButton_cargar_mis_pqrActionPerformed

    /**
     * @param args the command line arguments
     */
    
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ArquitecturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ArquitecturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ArquitecturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ArquitecturaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ArquitecturaUI().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog crear_pqrs;
    private javax.swing.JDialog info_solicitud;
    private javax.swing.JButton jButton_añadir_anotacion;
    private javax.swing.JButton jButton_cancelar_pqr;
    private javax.swing.JButton jButton_cargar_mis_pqr;
    private javax.swing.JButton jButton_crear_pqr;
    private javax.swing.JButton jButton_inicio_sesion;
    private javax.swing.JButton jButton_registro;
    private javax.swing.JComboBox<String> jComboBox_filtro_estado_solicitud;
    private javax.swing.JComboBox<String> jComboBox_filtro_tipo_solicitud;
    private javax.swing.JComboBox<String> jComboBox_solicitud_tipo;
    private com.toedter.calendar.JDateChooser jDateChooser_filtro_fecha_cierre;
    private com.toedter.calendar.JDateChooser jDateChooser_filtro_fecha_respuesta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_contraseña;
    private javax.swing.JLabel jLabel_correo;
    private javax.swing.JLabel jLabel_correo1;
    private javax.swing.JLabel jLabel_nombre;
    private javax.swing.JLabel jLabel_respuesta_login;
    private javax.swing.JLabel jLabel_respuesta_registro;
    private javax.swing.JLabel jLabel_solicitud;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_crear_pqr;
    private javax.swing.JPanel jPanel_iniciarsesion;
    private javax.swing.JPanel jPanel_inicio;
    private javax.swing.JPasswordField jPassword_inicio_sesion;
    private javax.swing.JPasswordField jPassword_registro;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTabbedPane jTabbedPane_inicio;
    private javax.swing.JTable jTable_info_pqrs;
    private javax.swing.JTextArea jTextArea_anotaciones;
    private javax.swing.JTextArea jTextArea_info_solicitud;
    private javax.swing.JTextArea jTextArea_solicitud_cuerpo;
    private javax.swing.JTextField jTextField_correo_inicio_sesion;
    private javax.swing.JTextField jTextField_correo_registro;
    private javax.swing.JTextField jTextField_nombre_registro;
    private javax.swing.JTextField jTextField_solicitud_asunto;
    private java.awt.Label label_pqrs;
    private java.awt.Label label_titulo;
    private java.awt.Panel panel1;
    private javax.swing.JPanel panel_formulario;
    private javax.swing.JPanel panel_formulario1;
    // End of variables declaration//GEN-END:variables
}
